#!/usr/bin/env python3
"""Build the single-file runtime from maintained sources, never a parallel rule set."""
from pathlib import Path
import argparse
import posixpath
import re
from urllib.parse import unquote

ROOT = Path(__file__).resolve().parents[1]
SOURCES = [
    'SKILL.md',
    'references/context-protocol.md', 'references/runtime-efficiency.md',
    'references/guided-production.md',
    'references/visual-baseline-and-tags.md',
    'references/prompt-writing.md', 'references/continuity-and-duration.md',
    'references/segment-ending.md',
    'references/asset-workflow.md',
    'references/local-asset-organization.md',
    'references/asset-image-standards.md', 'references/image-generation-clean-pass.md',
    'references/storyboard-reference-workflow.md',
    'references/result-repair.md', 'references/delivery-review.md',
    'references/guidance-samples.md', 'references/format-samples.md',
]
TARGET = 'references/universal-runtime.md'
EXAMPLE_SOURCES = {'references/guidance-samples.md', 'references/format-samples.md'}
MARKDOWN_LINK = re.compile(r'\[([^\]]+)\]\(([^)]+)\)')
LOCAL_START = '<!-- runtime:local-only:start -->'
LOCAL_END = '<!-- runtime:local-only:end -->'
LOCAL_MARKER = re.compile(re.escape(LOCAL_START) + '|' + re.escape(LOCAL_END))


def source_anchor(name):
    return 'runtime-' + re.sub(r'[^a-z0-9]+', '-', name.lower()).strip('-')


def local_link_target(source, target):
    """Resolve Markdown file links without treating web or fragment links as files."""
    if target.startswith('#') or re.match(r'^[A-Za-z][A-Za-z0-9+.-]*:', target):
        return None
    name = unquote(target.split('#', 1)[0])
    return posixpath.normpath(posixpath.join(posixpath.dirname(source), name))


def source_body(root, name):
    """Keep source prose verbatim except explicitly marked local-only material."""
    text = (Path(root) / name).read_text(encoding='utf-8')
    if name == 'SKILL.md':
        text = re.sub(r'\A---\n.*?\n---\n', '', text, count=1, flags=re.S)
    pieces, cursor, opened = [], 0, False
    for marker in LOCAL_MARKER.finditer(text):
        if marker.group() == LOCAL_START:
            if opened:
                raise ValueError(f'nested runtime local-only marker: {name}')
            pieces.append(text[cursor:marker.start()])
            opened = True
        else:
            if not opened:
                raise ValueError(f'unmatched runtime local-only marker: {name}')
            cursor = marker.end()
            opened = False
    if opened:
        raise ValueError(f'unclosed runtime local-only marker: {name}')
    pieces.append(text[cursor:])
    return ''.join(pieces).strip()


def portable_body(root, name):
    text = source_body(root, name)

    def rewrite_link(match):
        target = local_link_target(name, match.group(2))
        if target is None:
            return match.group()
        if target not in SOURCES:
            raise ValueError(f'single-file link target is not included: {name}: {target}; '
                             'mark optional local-only material explicitly')
        return f'[{match.group(1)}](#{source_anchor(target)})'

    return MARKDOWN_LINK.sub(rewrite_link, text)


def render(root=ROOT):
    sections = []
    for name in SOURCES:
        appendix = '示例附录\n\n' if name in EXAMPLE_SOURCES else ''
        sections.append(f'<!-- source: {name} -->\n'
                        f'<a id="{source_anchor(name)}"></a>\n\n'
                        f'{appendix}{portable_body(root, name)}')
    return ('<!-- GENERATED by scripts/build_runtime.py; edit source files, not this export. -->\n'
            '# 独立单文件运行版\n\n以下内容由当前规则源文件合并，运行规则与示例均在本文件内；'
            '历史日志不参与执行。按当前任务读取对应章节。'
            '本文件不附带本地维护脚本，执行创作规则不以本地脚本为前提。\n\n'
            + '\n\n---\n\n'.join(sections) + '\n')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    target = ROOT / TARGET
    try:
        expected = render()
    except (OSError, ValueError) as exc:
        print(f'BUILD UNAVAILABLE: {exc}')
        return 2
    if args.check:
        if not target.exists() or target.read_text(encoding='utf-8') != expected:
            print('STALE RUNTIME: regenerate with scripts/build_runtime.py')
            return 1
        print('RUNTIME MATCHES SOURCES (not a semantic test)')
    else:
        target.write_text(expected, encoding='utf-8')
        print('Runtime rebuilt from maintained sources')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
